import comp from "/Users/swtywang/Coding/05 我的博客/my-docs-new/src/.vuepress/.temp/pages/posts/杂货铺/01 安卓快应用.html.vue"
const data = JSON.parse("{\"path\":\"/posts/%E6%9D%82%E8%B4%A7%E9%93%BA/01%20%E5%AE%89%E5%8D%93%E5%BF%AB%E5%BA%94%E7%94%A8.html\",\"title\":\"安卓快应用\",\"lang\":\"zh-CN\",\"frontmatter\":{\"title\":\"安卓快应用\",\"date\":\"2023-07-12T00:00:00.000Z\",\"cover\":\"/assets/images/cover4.jpg\",\"headerMask\":\"rgba(40, 57, 101, .4)\",\"catalog\":true,\"tags\":[\"前端\"],\"gitInclude\":[],\"description\":\"参考资料： 快应用入门，看这篇就够了 什么是快应用？与原生 APP 相比优势在哪里? 快应用-技术调研 快应用厂商\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://swtywang/posts/%E6%9D%82%E8%B4%A7%E9%93%BA/01%20%E5%AE%89%E5%8D%93%E5%BF%AB%E5%BA%94%E7%94%A8.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"swtywang's homepage\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"安卓快应用\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"参考资料： 快应用入门，看这篇就够了 什么是快应用？与原生 APP 相比优势在哪里? 快应用-技术调研 快应用厂商\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:image\",\"content\":\"https://swtywang/assets/images/cover4.jpg\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"name\":\"twitter:card\",\"content\":\"summary_large_image\"}],[\"meta\",{\"name\":\"twitter:image:src\",\"content\":\"https://swtywang/assets/images/cover4.jpg\"}],[\"meta\",{\"name\":\"twitter:image:alt\",\"content\":\"安卓快应用\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"前端\"}],[\"meta\",{\"property\":\"article:published_time\",\"content\":\"2023-07-12T00:00:00.000Z\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"安卓快应用\\\",\\\"image\\\":[\\\"https://swtywang/assets/images/cover4.jpg\\\"],\\\"datePublished\\\":\\\"2023-07-12T00:00:00.000Z\\\",\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"swtywang\\\",\\\"url\\\":\\\"https:www.baidu.com\\\"}]}\"]]},\"headers\":[],\"readingTime\":{\"minutes\":0.28,\"words\":85},\"filePathRelative\":\"posts/杂货铺/01 安卓快应用.md\",\"localizedDate\":\"2023年7月12日\",\"excerpt\":\"<p>参考资料：</p>\\n<ol>\\n<li><a href=\\\"https://juejin.cn/post/6844903586971779080?searchId=202409221441301C35F5C366847F801E93\\\" target=\\\"_blank\\\" rel=\\\"noopener noreferrer\\\">快应用入门，看这篇就够了</a></li>\\n<li><a href=\\\"https://juejin.cn/post/7137222956324765709?searchId=202409221441301C35F5C366847F801E93\\\" target=\\\"_blank\\\" rel=\\\"noopener noreferrer\\\">什么是快应用？与原生 APP 相比优势在哪里?</a></li>\\n<li><a href=\\\"https://juejin.cn/post/6844903583415009294?searchId=202409221441301C35F5C366847F801E93\\\" target=\\\"_blank\\\" rel=\\\"noopener noreferrer\\\">快应用-技术调研</a></li>\\n<li><a href=\\\"https://www.quickapp.cn/\\\" target=\\\"_blank\\\" rel=\\\"noopener noreferrer\\\">快应用厂商</a></li>\\n</ol>\",\"autoDesc\":true}")
export { comp, data }

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
