import comp from "/Users/swtywang/Coding/05 我的博客/my-docs-new/src/.vuepress/.temp/pages/posts/QA/03 测试技术 - 可测性问题.html.vue"
const data = JSON.parse("{\"path\":\"/posts/QA/03%20%E6%B5%8B%E8%AF%95%E6%8A%80%E6%9C%AF%20-%20%E5%8F%AF%E6%B5%8B%E6%80%A7%E9%97%AE%E9%A2%98.html\",\"title\":\"测试技术 - 可测性问题\",\"lang\":\"zh-CN\",\"frontmatter\":{\"title\":\"测试技术 - 可测性问题\",\"date\":\"2021-08-01T00:00:00.000Z\",\"cover\":\"/assets/images/cover4.jpg\",\"headerMask\":\"rgba(40, 57, 101, .4)\",\"catalog\":true,\"tags\":[\"质量保障\"],\"gitInclude\":[],\"description\":\"\\\"可测性问题\\\"经常会出现在 QA 团队的 TOP 痛点问题中，针对这些问题的解决思路每个团队也不尽相同。这里会持续记录遇到过的典型可测性问题，并尝试做一些聚类 whiteboard_exported_image (7)whiteboard_exported_image (7) 一些思路 1. Mock Server/ Mock client 使用 Po...\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://swtywang/posts/QA/03%20%E6%B5%8B%E8%AF%95%E6%8A%80%E6%9C%AF%20-%20%E5%8F%AF%E6%B5%8B%E6%80%A7%E9%97%AE%E9%A2%98.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"swtywang's homepage\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"测试技术 - 可测性问题\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"\\\"可测性问题\\\"经常会出现在 QA 团队的 TOP 痛点问题中，针对这些问题的解决思路每个团队也不尽相同。这里会持续记录遇到过的典型可测性问题，并尝试做一些聚类 whiteboard_exported_image (7)whiteboard_exported_image (7) 一些思路 1. Mock Server/ Mock client 使用 Po...\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:image\",\"content\":\"https://swtywang/assets/images/cover4.jpg\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"name\":\"twitter:card\",\"content\":\"summary_large_image\"}],[\"meta\",{\"name\":\"twitter:image:src\",\"content\":\"https://swtywang/assets/images/cover4.jpg\"}],[\"meta\",{\"name\":\"twitter:image:alt\",\"content\":\"测试技术 - 可测性问题\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"质量保障\"}],[\"meta\",{\"property\":\"article:published_time\",\"content\":\"2021-08-01T00:00:00.000Z\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"测试技术 - 可测性问题\\\",\\\"image\\\":[\\\"https://swtywang.fun/minio//blog/e325063fad1b3d8fafc03c451ad30c59.png\\\"],\\\"datePublished\\\":\\\"2021-08-01T00:00:00.000Z\\\",\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"swtywang\\\",\\\"url\\\":\\\"https:www.baidu.com\\\"}]}\"]]},\"headers\":[{\"level\":3,\"title\":\"一些思路\",\"slug\":\"一些思路\",\"link\":\"#一些思路\",\"children\":[]}],\"readingTime\":{\"minutes\":1.16,\"words\":349},\"filePathRelative\":\"posts/QA/03 测试技术 - 可测性问题.md\",\"localizedDate\":\"2021年8月1日\",\"excerpt\":\"<blockquote>\\n<p>\\\"可测性问题\\\"经常会出现在 QA 团队的 TOP 痛点问题中，针对这些问题的解决思路每个团队也不尽相同。这里会持续记录遇到过的典型可测性问题，并尝试做一些聚类</p>\\n</blockquote>\\n<figure><img src=\\\"https://swtywang.fun/minio//blog/e325063fad1b3d8fafc03c451ad30c59.png\\\" alt=\\\"whiteboard_exported_image (7)\\\" tabindex=\\\"0\\\" loading=\\\"lazy\\\"><figcaption>whiteboard_exported_image (7)</figcaption></figure>\",\"autoDesc\":true}")
export { comp, data }

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
