import comp from "/Users/swtywang/Coding/05 我的博客/my-docs-new/src/.vuepress/.temp/pages/posts/QA/07 测试专项 - 监控治理、强弱依赖治理.html.vue"
const data = JSON.parse("{\"path\":\"/posts/QA/07%20%E6%B5%8B%E8%AF%95%E4%B8%93%E9%A1%B9%20-%20%E7%9B%91%E6%8E%A7%E6%B2%BB%E7%90%86%E3%80%81%E5%BC%BA%E5%BC%B1%E4%BE%9D%E8%B5%96%E6%B2%BB%E7%90%86.html\",\"title\":\"测试专项 - 监控治理、强弱依赖治理\",\"lang\":\"zh-CN\",\"frontmatter\":{\"title\":\"测试专项 - 监控治理、强弱依赖治理\",\"date\":\"2022-03-11T00:00:00.000Z\",\"cover\":\"/assets/images/cover4.jpg\",\"headerMask\":\"rgba(40, 57, 101, .4)\",\"catalog\":true,\"tags\":[\"质量保障\"],\"gitInclude\":[],\"description\":\"https://cloud.tencent.com/developer/article/1965803 https://segmentfault.com/a/1190000041720534?utm_source=sf-similar-article 监控： 业务监控：接口级自动注入、 基础服务监控：自动注入\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://swtywang/posts/QA/07%20%E6%B5%8B%E8%AF%95%E4%B8%93%E9%A1%B9%20-%20%E7%9B%91%E6%8E%A7%E6%B2%BB%E7%90%86%E3%80%81%E5%BC%BA%E5%BC%B1%E4%BE%9D%E8%B5%96%E6%B2%BB%E7%90%86.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"swtywang's homepage\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"测试专项 - 监控治理、强弱依赖治理\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"https://cloud.tencent.com/developer/article/1965803 https://segmentfault.com/a/1190000041720534?utm_source=sf-similar-article 监控： 业务监控：接口级自动注入、 基础服务监控：自动注入\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:image\",\"content\":\"https://swtywang/assets/images/cover4.jpg\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"name\":\"twitter:card\",\"content\":\"summary_large_image\"}],[\"meta\",{\"name\":\"twitter:image:src\",\"content\":\"https://swtywang/assets/images/cover4.jpg\"}],[\"meta\",{\"name\":\"twitter:image:alt\",\"content\":\"测试专项 - 监控治理、强弱依赖治理\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"质量保障\"}],[\"meta\",{\"property\":\"article:published_time\",\"content\":\"2022-03-11T00:00:00.000Z\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"测试专项 - 监控治理、强弱依赖治理\\\",\\\"image\\\":[\\\"https://swtywang/assets/images/cover4.jpg\\\"],\\\"datePublished\\\":\\\"2022-03-11T00:00:00.000Z\\\",\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"swtywang\\\",\\\"url\\\":\\\"https:www.baidu.com\\\"}]}\"]]},\"headers\":[],\"readingTime\":{\"minutes\":0.22,\"words\":65},\"filePathRelative\":\"posts/QA/07 测试专项 - 监控治理、强弱依赖治理.md\",\"localizedDate\":\"2022年3月11日\",\"excerpt\":\"<ul>\\n<li></li>\\n</ul>\\n<p><a href=\\\"https://cloud.tencent.com/developer/article/1965803\\\" target=\\\"_blank\\\" rel=\\\"noopener noreferrer\\\">https://cloud.tencent.com/developer/article/1965803</a></p>\\n<p><a href=\\\"https://segmentfault.com/a/1190000041720534?utm_source=sf-similar-article\\\" target=\\\"_blank\\\" rel=\\\"noopener noreferrer\\\">https://segmentfault.com/a/1190000041720534?utm_source=sf-similar-article</a></p>\",\"autoDesc\":true}")
export { comp, data }

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
